### ISSUE TITLE
Differences from parse

### ISSUE THREAD

**Issue by randallpittman** [tfeldmann/simplematch#1]
Hi! Great library. Seems quite similar to [parse](https://github.com/r1chardj0n3s/parse) - are you familiar with that one? If so, what would you say differentiates the two?

**Comment by tfeldmann** [comment]
Oh wow, did not know that one! Looks a bit more complicated, but very similar in some cases. I'll look into it and thank your for the hint!

**Comment by tfeldmann** [comment]
Some differences I found.

`simplematch`
- returns dict directly instead of `<Result>` classes
- simpler, more readable syntax (ymmv)
- less specific parsing functionality (misses some features like matching ints of specific length)
- has uncaptured wildcards
- less code
- I'll guess it's faster. But I'd have to prove that.
- global type registration

I somehow missed `parse` completely when I was developing this. So if you need some of the advanced functionality it looks like a great option. I think `simplematch` is a bit more intuitive to use, but I'm biased of course 😅
